### ISSUE TITLE
Inheriting css color doesn't work

### ISSUE THREAD

**Issue by xamiam** [alexwebgr/faw_icon#2]
I am using the icons.json approach. The fill of the icons is not the same as the text color surrounding the svg. Am I missing out on something?

**Comment by alexwebgr** [comment]
hey xamiam,

can you post some code ?
i am not sure what you are trying to achieve !

thanks
alex

p.s.
https://fontawesome.com/how-to-use/on-the-web/referencing-icons/basic-use#with-your-styling

**Comment by xamiam** [comment]
hi alex,

I figured out you can inherit the color by setting:

```
svg {
  fill: currentColor;
}
```

this needs to be done separately when not using the original fontawesome css.

thank you so much!

max.
