### ISSUE TITLE
Add support for new Duotone icons

### ISSUE THREAD

**Issue by deikka** [alexwebgr/faw_icon#3]
Hi, 

It would be cool to add support for Duotone icons. I've been looking and seems easy, may be it works only adding the case to the helper?

```ruby
 def fa_style(style)
    case style
      when 'solid'
        'fas'
      when 'regular'
        'far'
      when 'light'
        'fal'
      when 'brands'
        'fab'
      when 'duotone'
        'fad'
    end
  end
```
Thanks in advance!

**Comment by alexwebgr** [comment]
hi @deikka 
feel free to submit a pull request

thanks
alex

**Comment by deikka** [comment]
Done! :)

**Comment by alexwebgr** [comment]
https://github.com/alexwebgr/faw_icon/pull/4
